### ISSUE TITLE
Undeclared dependencies

### ISSUE THREAD

**Issue by eserte** [dragosv/serge-plugins#11]
The test suite fails if some prereqs are not installed: Clone and Env. The latter is usually part of a normal perl installation, but some linux distributions may ship a perl without Env.pm (e.g. CentOS 7).

**Comment by dragosv** [comment]
@eserte I pushed a version that should fix the issue. If it does not, please post the command you are running and the output you are getting.

**Comment by dragosv** [comment]
@eserte closing the issue. If there is still a problem please raise another one.

**Comment by eserte** [comment]
So far I did not see the problem again...
